# Build APKs for Kiwi Browser Next
name: 'Main branch: Deploy updated logos'

# Controls when the action will run. Triggers the workflow on pull request events or manual trigger
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.8
    
      - name: Deploying logos from GitHub
        run: curl --http1.0 --no-buffer -s 'http://${{ secrets.DEPLOY_SERVER }}/deploy_logos.php?deploy_key=${{ secrets.DEPLOY_KEY }}&git_user=${{ github.repository_owner }}&git_repository=${{ github.event.repository.name }}&git_runid=${{ github.run_id }}&git_branch=${{ steps.branch-name.outputs.current_branch }}'

