# Deploy logos to production cache server
name: 'Fetch favicon and upload on repo'

# Controls when the action will run. Triggers the workflow on pull request events or manual trigger
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Url domain like "kiwibrowser.net"'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - id: get-id
        run: |
          id=$(echo ${{ github.event.inputs.url }} | cut -c1)
          echo "::set-output name=id::$id"
      - name : Create dir path 
        run: sudo mkdir -p /assets/${{steps.get-id.outputs.id}}
      - name: Get favicon and save to temp image
        run: curl -Ls -w %{url_effective} -o "./assets/${{steps.get-id.outputs.id}}/${{ github.event.inputs.url }}.png" "https://besticon-demo.herokuapp.com/icon?url=${{ github.event.inputs.url }}&size=32..50..128" 

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          # Commit message
          commit_message: Add ${{ github.event.inputs.url }}.png icon
          file_pattern: ./*.png
